### ISSUE TITLE
`development restore-from production` doesn't map relationships correctly

### ISSUE THREAD

**Issue by BrandonKlotz** [chiperific/liters_tracker#20]
- `development restore-from production` doesn't map relationships correctly? Is this a mis-matched PG version between me and Heroku?

**Comment by Crevax** [comment]
@chiperific Do you have more details about what wasn't correct with the relationship mapping? I was able to use Parity to pull down a production database and restore it on my local installation of Postgres, but I don't know if that means I was able to avoid the issues you had.
