### ISSUE TITLE
Devise Mail does not send

### ISSUE THREAD

**Issue by BrandonKlotz** [chiperific/liters_tracker#22]
- Devise mail doesn't send? Mailgun shows nothing going out.

**Comment by chiperific** [comment]
Frankly, we could scale back Devise to just sign in/out and disable:
* Confirmations
* Password resetting by email
* Sign up

Then we wouldn't need email integration at all.

**Comment by chiperific** [comment]
Please also strip out any excess Devise features on `user.rb`

**Comment by chiperific** [comment]
Fixed by PR #51
