### ISSUE TITLE
`sessions/new?return-to` doesn't do anything

### ISSUE THREAD

**Issue by BrandonKlotz** [chiperific/liters_tracker#24]
- `sessions/new?return-to` doesn't do anything

**Comment by chiperific** [comment]
In previous apps, if an un-signed-in user tried to hit a URL that requires `current_user`, I would redirect them to `sessions/new` and add a `return-to=#URL` so I could navigate them back to where they were.

To implement this, we need `session/create` to look for a `return-to` param and navigate the newly-signed-in user to that destination.
