### ISSUE TITLE
Add Basic Stat Block component

### ISSUE THREAD

**Issue by BrandonKlotz** [chiperific/liters_tracker#28]
**Describe the solution you'd like**
As a developer, I'd like to be able to reuse a HTML partial for stat blocks on different views.

It should accept data, title, possibly styling attributes as well.
<img width="161" alt="Screen Shot 2019-08-17 at 12 06 33 PM" src="https://user-images.githubusercontent.com/19940878/63214570-ae8d8780-c0e7-11e9-80b2-465c031fd622.png">

**Comment by chiperific** [comment]
It's there!!!
