### ISSUE TITLE
As a User, I'd like to write stories with images related to Reports

### ISSUE THREAD

**Issue by BrandonKlotz** [chiperific/liters_tracker#29]
**Is your feature request related to a problem? Please describe.**
In designing a dashboard, we'd like visitors to be able to click Reports that are shown in the public dashboard and view stories that are connected to the reports. 

**Describe the solution you'd like**
A user should be able to upload images, write a few sentences of rich-text and connect them to reports.

**Comment by chiperific** [comment]
This is now a thing. It works. So we're done.
