### ISSUE TITLE
As a noob, I would like to have documentation for everything that is incomplete

### ISSUE THREAD

**Issue by chiperific** [chiperific/liters_tracker#70]

**Comment by chiperific** [comment]
AWS:
* Console login link: https://667992170958.signin.aws.amazon.com/console
* Virtual Private Cloud: https://us-east-2.console.aws.amazon.com/vpc/home?region=us-east-2#
* Relational Db: https://us-east-2.console.aws.amazon.com/rds/home?region=us-east-2#
* CloudFront: https://console.aws.amazon.com/cloudfront/home?region=us-east-2

**Comment by chiperific** [comment]
`@story.prominent?` needs special styling for highlighting on Dashboard#index and Story#show

**Comment by zkendra** [comment]
Handling of Thumbnails

Today when an image is uploaded for a story, 2 files are saved to S3 (a raw version and thumbnail) however, the thumbnail saved as the same resolution as the raw.

Proper handling of thumbnails is missing, the 'save_image' method in the Story controll should lowering the resolution of the raw image, retaining the dimensions of the image and save the result as the thumbnail.

Potentially helpful references: 
https://cloudinary.com/blog/image_optimization_in_ruby

**Comment by chiperific** [comment]
Closed
